# Generated by Django 2.0.7 on 2018-08-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFreinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('datetime_request', models.DateTimeField()),
                ('datetime_accept', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accept', 'Принят'), ('deny', 'Отказ'), ('none', 'Запрос')], default='none', max_length=6)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_freinds_send', to='users.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_freinds_recv', to='users.User')),
            ],
        ),
    ]
