# Generated by Django 2.0.7 on 2018-08-01 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180801_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('datetime_request', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_accept', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accept', 'Принят'), ('deny', 'Отказ'), ('none', 'Запрос')], default='none', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestfreind',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='requestfreind',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='freinds',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='users.User'),
        ),
        migrations.DeleteModel(
            name='RequestFreind',
        ),
        migrations.AddField(
            model_name='requestfriend',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_friends_send', to='users.User'),
        ),
        migrations.AddField(
            model_name='requestfriend',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_friends_recv', to='users.User'),
        ),
    ]
